apiVersion: v1
kind: Pod
metadata:
  name: static-jvm-debug
spec:
  containers:
  - name: jvm-debug
    image: jvm-debug:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
    env:
    - name: MAX
      value: "100000"
